apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: movies-api
spec:
  selector:
    matchLabels:
      app: movies-api
  template:
    metadata:
      labels:
        app: movies-api
        timestamp: "$TIMESTAMP"
    spec:
      containers:
      - name: movies-api
        image: smithchan/movies-api
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          timeoutSeconds: 5
          periodSeconds: 30
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          timeoutSeconds: 5
          periodSeconds: 30
          initialDelaySeconds: 10
      imagePullSecrets:
      - name: regsecret
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:iam::392867588173:server-certificate/cloudfront/smithsonianearthtv"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    external-dns.alpha.kubernetes.io/hostname: movies-api-$ENV.smithsonianearthtv.com.
  name: movies-api
  labels:
    app: movies-api
spec:
  type: LoadBalancer
  ports:
    - name: "http"
      port: 80
      targetPort: 8080
      protocol: "TCP"
    - name: "https"
      port: 443
      targetPort: 8080
      protocol: "TCP"
  selector:
    app: movies-api